name: Push to master branch

on:
  push:
    branches: [ master ]

concurrency: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: anna-money/action-bump-version@master
        id: bump
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          with_month: true
          add_tag: true
      - run: echo "${{ steps.bump.outputs.old_tag }} -> ${{ steps.bump.outputs.new_tag }}"
      - name: Raise error if version hasn't bumped
        if: ${{ !steps.bump.outputs.new_tag }}
        run: exit 1
