name: Pull requests

on:
  pull_request:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Run local action
        uses: ./
        id: bump
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          with_month: true
          add_tag: false
      - run: echo "${{ steps.bump.outputs.old_tag }} -> ${{ steps.bump.outputs.new_tag }}"
      - name: Raise error if version hasn't bumped
        if: ${{ !steps.bump.outputs.new_tag }}
        run: exit 1
